# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GJyZ-3PAoGo-eNk21MVPuiYL1kDpuOTw
"""

import numpy as np
import matplotlib.pyplot as plt

# ---------------- XOR Dataset ----------------
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([[0],
              [1],
              [1],
              [0]])

# ---------------- Seed for reproducibility ----------------
np.random.seed(1)

# ---------------- Initialize weights and biases ----------------
W1 = np.random.randn(2, 2)  # input to hidden weights
b1 = np.zeros((1, 2))       # hidden layer bias
W2 = np.random.randn(2, 1)  # hidden to output weights
b2 = np.zeros((1, 1))       # output layer bias

# ---------------- Activation functions ----------------
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(output):
    return output * (1 - output)  # derivative from activated output

# ---------------- Hyperparameters ----------------
lr = 0.1       # learning rate
epochs = 10000 # training iterations

# ---------------- Training loop ----------------
losses = []

for i in range(epochs):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)                 # hidden layer activation
    z2 = np.dot(a1, W2) + b2
    output = sigmoid(z2)             # output layer activation

    # Compute error
    error = y - output
    losses.append(np.mean(error**2)) # track loss for plotting

    # Backpropagation
    d_output = error * sigmoid_derivative(output)
    d_hidden = d_output.dot(W2.T) * sigmoid_derivative(a1)

    # Update weights and biases
    W2 += a1.T.dot(d_output) * lr
    b2 += np.sum(d_output, axis=0, keepdims=True) * lr
    W1 += X.T.dot(d_hidden) * lr
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * lr

# ---------------- Print final predictions ----------------
print("Final Predictions (rounded):")
print(np.round(output, 2))

# ---------------- Plot Loss Curve ----------------
plt.figure(figsize=(6,4))
plt.plot(losses)
plt.title("Training Loss Over Epochs")
plt.xlabel("Epochs")
plt.ylabel("Mean Squared Error")
plt.grid(True)
plt.show()

# ---------------- Plot Decision Boundary ----------------
xx, yy = np.meshgrid(np.linspace(-0.5, 1.5, 200), np.linspace(-0.5, 1.5, 200))
grid = np.c_[xx.ravel(), yy.ravel()]

# Forward pass on grid
a1_grid = sigmoid(np.dot(grid, W1) + b1)
output_grid = sigmoid(np.dot(a1_grid, W2) + b2)
output_grid = output_grid.reshape(xx.shape)

plt.figure(figsize=(6,6))
plt.contourf(xx, yy, output_grid, levels=[-0.1,0.5,1.1], colors=['#FFAAAA','#AAAAFF'], alpha=0.6)
plt.scatter(X[:,0], X[:,1], c=y.flatten(), edgecolors='k', s=100)
plt.title("XOR Neural Network Decision Boundary")
plt.xlabel("Input 1")
plt.ylabel("Input 2")
plt.show()