# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m_QK-i0PMhUlR5eGMFkTf6q2VAu9HxI8
"""

import numpy as np
import matplotlib.pyplot as plt
from collections import Counter

# ---------------- 1D DATA ----------------
X_train_1d = np.array([[1],[2],[3],[6],[7],[8]])
y_train_1d = np.array([0,0,0,1,1,1])
X_test_1d = np.array([[4]])

# ---------------- 2D DATA ----------------
X_train_2d = np.array([[1,1],[2,1],[3,2],[6,5],[7,5],[8,6]])
y_train_2d = np.array([0,0,0,1,1,1])
X_test_2d = np.array([[4,3]])

# ---------------- FUNCTIONS ----------------
def euclidean_distance(a, b):
    return np.sqrt(np.sum((a-b)**2))

def predict(X_train, y_train, X_test, k=3):
    y_pred = []
    for test_point in X_test:
        distances = [euclidean_distance(test_point, x) for x in X_train]
        nearest_indices = np.argsort(distances)[:k]
        nearest_labels = y_train[nearest_indices]
        predicted_label = Counter(nearest_labels).most_common(1)[0][0]
        y_pred.append(predicted_label)
    return np.array(y_pred)

# ---------------- PREDICTIONS ----------------
pred_1d = predict(X_train_1d, y_train_1d, X_test_1d)
pred_2d = predict(X_train_2d, y_train_2d, X_test_2d)

print("1D Prediction for", X_test_1d.flatten(), ":", pred_1d)
print("2D Prediction for", X_test_2d.flatten(), ":", pred_2d)

# ---------------- 1D VISUALIZATION ----------------
plt.figure(figsize=(8,2))
plt.scatter(X_train_1d[y_train_1d==0], np.zeros_like(X_train_1d[y_train_1d==0]), c='red', label='Class 0', s=100)
plt.scatter(X_train_1d[y_train_1d==1], np.zeros_like(X_train_1d[y_train_1d==1]), c='blue', label='Class 1', s=100)
plt.scatter(X_test_1d, np.zeros_like(X_test_1d), c='green', marker='*', s=200, label='Test Point')

x_grid = np.linspace(0, 9, 500).reshape(-1,1)
y_grid = predict(X_train_1d, y_train_1d, x_grid, k=3)
plt.fill_between(x_grid.flatten(), -0.1, 0.1, where=(y_grid==0), color='red', alpha=0.2)
plt.fill_between(x_grid.flatten(), -0.1, 0.1, where=(y_grid==1), color='blue', alpha=0.2)

plt.title("1D KNN Visualization (k=3)")
plt.xlabel("Feature")
plt.yticks([])
plt.legend()
plt.show()

# ---------------- 2D VISUALIZATION ----------------
plt.figure(figsize=(6,6))
# Plot training points
plt.scatter(X_train_2d[y_train_2d==0,0], X_train_2d[y_train_2d==0,1], c='red', label='Class 0', s=100)
plt.scatter(X_train_2d[y_train_2d==1,0], X_train_2d[y_train_2d==1,1], c='blue', label='Class 1', s=100)
plt.scatter(X_test_2d[0,0], X_test_2d[0,1], c='green', marker='*', s=200, label='Test Point')

# Create decision boundary
xx, yy = np.meshgrid(np.linspace(0, 9, 200), np.linspace(0, 7, 200))
grid = np.c_[xx.ravel(), yy.ravel()]
y_grid_2d = predict(X_train_2d, y_train_2d, grid, k=3).reshape(xx.shape)
plt.contourf(xx, yy, y_grid_2d, levels=[-0.1,0.5,1.1], colors=['#FFAAAA','#AAAAFF'], alpha=0.3)

plt.title("2D KNN Visualization (k=3)")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.legend()
plt.show()